server:
  port: 10002
  # ssl:
  #   enabled: true
  #   key-store: classpath:certificate.p12
  #   key-store-type: PKCS12
  #   key-store-password: "something"
  #   key-alias: something
  #   trust-store: classpath:certificate.p12
  #   trust-store-password: "something"
spring:
  application:
    name: hello-service
  cloud:
    consul:
      enabled: true
  endpoints:
    actuator:
      sensitive: false
management:
  security:
    enabled: false
  server:
    port: 10003
    ssl:
      enabled: false